CREATE TABLE jobs(
id BIGSERIAL PRIMARY KEY NOT NULL,
title VARCHAR(80) NOT NULL
);
CREATE TABLE employers(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(80) NOT NULL,
    degree VARCHAR(80) NOT NULL,
    salary NUMERIC(15) NOT NULL,
    job_id BIGINT REFERENCES jobs(id)
    );